title = "gitleaks config"

[[rules]]
id = "generic-credential"
description = "Generic Credential"
regex = '''(?i)(password|passwd|pwd|secret|key|token|auth)[a-z0-9_ .\-=]{0,25}[:=][^a-z0-9_ \-=]*'''
tags = ["cred", "generic"]

